---
- hosts: mywebserver 
  become: yes 
  gather_facts: yes
  tasks: 

  - name: i want to install apache2 on ubuntu
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want ti start apache2 on ubuntu
    service: 
      name: "{{mywebpackonubuntu}}"
      state: restarted 
    when: ansible_os_family=="Debian"

  - name: i want to install webserver redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"
    
  - name: i want to start webserver redhat
    service:
       name: "{{mywebpackonredhat}}"
       state: started 
    when: ansible_os_family=="RedHat"    

